Feature/main page mine ntu card
MinecraftNTU/dashboard-v1 pull request #5
Opened 2021-06-03 13:46 UTC by jc-hiroto

- Add cards to index page (main-page) for user to access different services.

2021-06-03 18:34 UTC, maxchou415 requested changes

2021-06-03 18:34 UTC, maxchou415 commented on nuxt.config.js
> +    '@nuxtjs/fontawesome'
沒有用的套件要刪掉 😂

2021-06-03 18:34 UTC, maxchou415 commented on nuxt.config.js
> +      { rel: 'stylesheet', href: 'https://unpkg.com/tachyons@4.12.0/css/tachyons.min.css' },
這也是

2021-06-03 18:34 UTC, maxchou415 commented on package.json
> +    "@nuxtjs/fontawesome": "^1.1.2",
刪刪刪

2021-06-05 10:32 UTC, jc-hiroto commented
@maxchou415 deleted.

2021-06-05 13:29 UTC, closed without merging